name: Upload Website

on:
  push:
    branches: ["production", "staging"]
  pull_request:
    branches: ["production", "staging"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # or '18' as per your requirement

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Remove node_modules and package-lock.json
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      - name: Configure npm to use private registry
        run: |
          echo "@tiptap-pro:registry=https://registry.tiptap.dev/" >> ~/.npmrc
          echo "//registry.tiptap.dev/:_authToken=${{ secrets.TIPTAP_PRO_TOKEN }}" >> ~/.npmrc

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build app
        run: npm run build

      - name: Set S3 bucket based on branch or pull request
        id: set_bucket
        run: |
          # Determine branch for pull request or push event
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BRANCH_NAME="${{ github.event.pull_request.base.ref }}"
          else
            BRANCH_NAME="${{ github.ref_name }}"
          fi

          # Set S3 bucket based on branch
          if [[ "$BRANCH_NAME" == "staging" ]]; then
            echo "S3_BUCKET=${{ secrets.AWS_S3_BUCKET_STAGING }}" >> $GITHUB_ENV
            echo "BUCKET_ENVIRONMENT=staging" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == "production" ]]; then
            echo "S3_BUCKET=${{ secrets.AWS_S3_BUCKET_PRODUCTION }}" >> $GITHUB_ENV
            echo "BUCKET_ENVIRONMENT=production" >> $GITHUB_ENV
          else
            echo "Error: Unsupported branch $BRANCH_NAME" >&2
            exit 1
          fi

      - name: Log the S3 bucket
        run: |
          echo "The S3 bucket environment is set to: ${{ env.BUCKET_ENVIRONMENT }}"

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: ""
        env:
          SOURCE_DIR: dist/
          AWS_S3_BUCKET: ${{ env.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Log the uploaded S3 bucket
        run: |
          echo "The changes have been uploaded to the S3 bucket corresponding to: ${{ env.BUCKET_ENVIRONMENT }}"
